version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  django:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
      - media_volume:/backend/images
    depends_on:
      - psql

  react:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
    environment:
      - WATCHPACK_POOLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  static_volume:
  media_volume: